version: '3.1'

services:
  todo-database:
    image: todo-database:0.0.1
    networks:
      - todo-network

  todo-backend:
    image: todo-backend:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - todo-database
    networks:
      - todo-network

  todo-frontend:
    image: todo-frontend:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - todo-backend
    networks:
      - todo-network

networks:
  todo-network: {}
