apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: patientfile-backend
spec:
  containers:
  - image: xdRico/hsr_patientenakte_24_patientfile_backend:0.1
    name: patientfile-backend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
