apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: patientfile-database
spec:
  containers:
  - image: xdRico/hsr_patientenakte_24_patientfile_database:0.1
    name: patientfile-database
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
