apiVersion: v1
kind: Service
metadata:
  name: patientfile-backend-service
  labels:
    app: patientfile-backend
spec:
  type: ClusterIP
  selector:
     app: patientfile-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080