apiVersion: v1
kind: Service
metadata:
  name: patientfile-database-service
  labels:
    app: patientfile-database
spec:
  type: ClusterIP
  selector:
     app: patientfile-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432