apiVersion: v1
kind: Service
metadata:
  name: patientfile-frontend-service
  labels:
    app: patientfile-frontend
spec:
  type: LoadBalancer
  selector:
     app: patientfile-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081